version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_bot
    volumes:
      - .:/app
    environment:
      - DISPLAY=:99
    restart: always
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
